# Generated by Django 5.2.7 on 2025-10-22 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('F', 'Feminin'), ('G', 'Masculin')], max_length=2)),
                ('numero_inscription', models.CharField(max_length=50, unique=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='classe.classe')),
            ],
        ),
    ]
