# Generated by Django 5.2.7 on 2025-10-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve',
            old_name='numero_inscription',
            new_name='matricule',
        ),
        migrations.RenameField(
            model_name='eleve',
            old_name='date_naissance',
            new_name='naissance',
        ),
    ]
