# Generated by Django 5.2.7 on 2025-10-24 17:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleve', '0001_initial'),
        ('enseignant', '0001_initial'),
        ('matiere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('Trimestre 1', 'Trimestre 1'), ('Trimestre 2', 'Trimestre 2'), ('Trimestre 3', 'Trimestre 3')], default='Trimestre 1', max_length=12)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('appreciation', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='eleve.eleve')),
            ],
            options={
                'unique_together': {('eleve', 'session')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('Trimestre 1', 'Trimestre 1'), ('Trimestre 2', 'Trimestre 2'), ('Trimestre 3', 'Trimestre 3')], default='Trimestre 1', max_length=12)),
                ('typeNote', models.CharField(choices=[('Note 1', 'Note 1'), ('Note 2', 'Note 2'), ('Examen', 'Examen')], max_length=120)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='eleve.eleve')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enseignant.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matiere.matiere')),
            ],
            options={
                'unique_together': {('eleve', 'matiere', 'session', 'typeNote')},
            },
        ),
    ]
