# Generated by Django 5.2.7 on 2025-10-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletin',
            old_name='dateGeneration',
            new_name='date_generation',
        ),
        migrations.RenameField(
            model_name='bulletin',
            old_name='moyenneGenerale',
            new_name='moyenne_generale',
        ),
    ]
